-- PostgreSQL Script

CREATE TABLE Users (
  id SERIAL PRIMARY KEY,
  userId VARCHAR(50) UNIQUE NOT NULL,
  username VARCHAR(100) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  address TEXT NOT NULL,
  city VARCHAR(100) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Orders (
  id SERIAL PRIMARY KEY,
  orderId VARCHAR(50) UNIQUE NOT NULL,
  userId VARCHAR(50) NOT NULL REFERENCES Users(userId),
  mobileNumber VARCHAR(10) NOT NULL,
  cartItems JSONB NOT NULL,
  subtotal DECIMAL(10, 2) NOT NULL,
  deliveryFee DECIMAL(10, 2) NOT NULL,
  totalAmount DECIMAL(10, 2) NOT NULL,
  status VARCHAR(20) DEFAULT 'Confirmed',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
